// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-VR_srnPwnXjDS5GXET3xjzV1zo1LDdo',
    appId: '1:728079332235:web:bd1c8397fa76f3fd88b58e',
    messagingSenderId: '728079332235',
    projectId: 'hk-project-6e989',
    authDomain: 'hk-project-6e989.firebaseapp.com',
    storageBucket: 'hk-project-6e989.firebasestorage.app',
    measurementId: 'G-2HD703584R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPViSHIFwrMIXyks9izEetjOb9rJazhoM',
    appId: '1:728079332235:android:277869f23a5a94d488b58e',
    messagingSenderId: '728079332235',
    projectId: 'hk-project-6e989',
    storageBucket: 'hk-project-6e989.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWvmMrrLbUl_WsKzs5Eq62WicAHn8g_iA',
    appId: '1:728079332235:ios:5f884974e533c3a188b58e',
    messagingSenderId: '728079332235',
    projectId: 'hk-project-6e989',
    storageBucket: 'hk-project-6e989.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWvmMrrLbUl_WsKzs5Eq62WicAHn8g_iA',
    appId: '1:728079332235:ios:5f884974e533c3a188b58e',
    messagingSenderId: '728079332235',
    projectId: 'hk-project-6e989',
    storageBucket: 'hk-project-6e989.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-VR_srnPwnXjDS5GXET3xjzV1zo1LDdo',
    appId: '1:728079332235:web:5e3b683d8f05b1b488b58e',
    messagingSenderId: '728079332235',
    projectId: 'hk-project-6e989',
    authDomain: 'hk-project-6e989.firebaseapp.com',
    storageBucket: 'hk-project-6e989.firebasestorage.app',
    measurementId: 'G-EH600R23MH',
  );
}
